-- Standalone PostgreSQL schema for this bot.
-- It is mounted into a brand-new PostgreSQL volume when the DB container starts.

BEGIN;

CREATE TABLE users (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    telegram_id BIGINT NOT NULL UNIQUE,
    email TEXT,
    state TEXT,
    total_spent INTEGER NOT NULL DEFAULT 0 CHECK (total_spent >= 0),
    link TEXT,
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE INDEX users_state_idx ON users (state);
CREATE INDEX users_link_idx ON users (link) WHERE link IS NOT NULL;

CREATE TABLE invite_links (
    link TEXT PRIMARY KEY,
    followed INTEGER NOT NULL DEFAULT 0 CHECK (followed >= 0)
);

CREATE TABLE referrals (
    user_id BIGINT PRIMARY KEY REFERENCES users (id),
    invited_by BIGINT NOT NULL REFERENCES users (id),
    activated BOOLEAN NOT NULL DEFAULT FALSE,
    reward_given BOOLEAN NOT NULL DEFAULT FALSE,
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    activated_at TIMESTAMPTZ,
    reward_given_at TIMESTAMPTZ,
    CONSTRAINT referrals_no_self_referral CHECK (user_id <> invited_by),
    CONSTRAINT referrals_reward_requires_activation
        CHECK (NOT reward_given OR activated)
);

CREATE INDEX referrals_invited_by_idx ON referrals (invited_by);

CREATE TABLE appstore_transactions (
    transaction_id TEXT PRIMARY KEY,
    user_id BIGINT NOT NULL REFERENCES users (id),
    telegram_id BIGINT REFERENCES users (telegram_id),
    email TEXT,
    amount INTEGER NOT NULL CHECK (amount > 0),
    source TEXT NOT NULL CHECK (source IN ('site', 'tma', 'bot')),
    created_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE INDEX appstore_transactions_created_at_idx ON appstore_transactions (created_at);
CREATE INDEX appstore_transactions_user_id_idx ON appstore_transactions (user_id);

CREATE TABLE processed_payments (
    payment_id TEXT PRIMARY KEY,
    created_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE TABLE used_codes (
    code TEXT PRIMARY KEY,
    nominal INTEGER NOT NULL CHECK (nominal > 0),
    transaction_id TEXT UNIQUE REFERENCES appstore_transactions (transaction_id),
    user_id BIGINT NOT NULL REFERENCES users (id),
    telegram_id BIGINT REFERENCES users (telegram_id),
    email TEXT,
    purpose TEXT NOT NULL CHECK (purpose IN ('purchase', 'referral_reward')),
    source TEXT CHECK (source IN ('site', 'tma', 'bot')),
    issued_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    CONSTRAINT used_codes_transaction_for_purchase
        CHECK (
            (purpose = 'purchase' AND transaction_id IS NOT NULL)
            OR (purpose = 'referral_reward' AND transaction_id IS NULL)
        )
);

CREATE INDEX used_codes_user_id_idx ON used_codes (user_id);

CREATE TABLE media_cache (
    key TEXT PRIMARY KEY,
    file_id TEXT NOT NULL,
    kind TEXT NOT NULL,
    updated_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE TABLE survey_bonus (
    user_id BIGINT PRIMARY KEY REFERENCES users (telegram_id),
    completed_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE TABLE bot_flags (
    key TEXT PRIMARY KEY,
    enabled BOOLEAN NOT NULL DEFAULT FALSE
);

CREATE TABLE scheduled_announcements (
    weekday SMALLINT PRIMARY KEY,
    send_time TIME NOT NULL,
    audience TEXT NOT NULL CHECK (audience IN ('all', 'paid', 'rfool', 'others')),
    source_chat_id BIGINT NOT NULL,
    source_message_id BIGINT NOT NULL,
    created_by BIGINT NOT NULL,
    enabled BOOLEAN NOT NULL DEFAULT TRUE,
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    last_sent_at TIMESTAMPTZ,
    last_success INTEGER,
    last_failed INTEGER,
    CONSTRAINT scheduled_announcements_weekday_check
        CHECK (weekday BETWEEN 0 AND 6)
);

CREATE TABLE alfa_orders (
    order_number TEXT PRIMARY KEY,
    user_id BIGINT NOT NULL,
    chat_id BIGINT NOT NULL,
    nominal INTEGER NOT NULL,
    amount_kopecks INTEGER NOT NULL,
    md_order TEXT,
    source TEXT,
    created_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE TABLE robokassa_orders (
    invoice_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT NOT NULL,
    chat_id BIGINT NOT NULL,
    nominal INTEGER NOT NULL,
    amount_rub INTEGER NOT NULL,
    source TEXT,
    created_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

COMMIT;
